spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ciencia_br
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.hibernate.ddl-auto=update
